### ISSUE TITLE
Allow specifying what API URl to post to 

### ISSUE THREAD

**Issue by GrumpyBear57** [LiveTL/kanatran#6]
As far as I understand, currently the API URL is hardcoded to `api.livetl.app`, however I'd like to be able to run Kanatran to test my local development instance of the API. 
Something as simple as `API_URL='localhost'` in `.env`, then fallback to `api.livetl.app` when not present would be good enough for me.

**Comment by KentoNishi** [comment]
Done

**Comment by GrumpyBear57** [comment]
I don't think the .env var should be called `LIVETL_API_URL` since half the point of the var is so that people can point to *not* the LiveTL API (the other half so that I can use it to point to my local API instance). I think just `API_URL` would be a better name.
