### ISSUE TITLE
Container stops processing after a period of time

### ISSUE THREAD

**Issue by GrumpyBear57** [LiveTL/kanatran#8]
After ~10 minutes of running, I get this, then nothing else. I encountered this on 3 different containers processing 3 different streams. I'm assuming (based on timing) this is something to do with how you send a keep alive ping to the API. 

```
INFO:     127.0.0.1:50234 - "POST /logs HTTP/1.1" 200 OK
{"timestamp":880.738,"text":"やばいこと言ってた。","translation":"I was saying something bad."}
INFO:     127.0.0.1:50264 - "POST /logs HTTP/1.1" 200 OK

INFO:     127.0.0.1:50264 - "POST /logs HTTP/1.1" 200 OK
INFO:     127.0.0.1:50300 - "GET /static/index.html HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:50300 - "GET /static/index.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:50300 - "GET /env HTTP/1.1" 200 OK
{SESSION KEY}
INFO:     127.0.0.1:50300 - "POST /logs HTTP/1.1" 200 OK
```

I don't know if the session key that was printed here is the same key as the one that was obtained before or not.

**Comment by GrumpyBear57** [comment]
So I tried to process a VOD again, and this time instead of getting a session key in the log file, I just got the GET request to index.html returning a 304 response. I also kept  a closer eye on when the TLs stopped coming in, and it seemed to be around a minute or two before then, so I'm not sure if it's related or not (especially since it's technically over the 10 min keep-alive mark). Would be nice to have more logging to be able to see what or why it is failing.

**Comment by GrumpyBear57** [comment]
Very interesting, the container has started adding translations again (after opening a new session even). The timestamp has also been reset back to zero, and is incrementing from there again. 
I've also noticed I periodically get an error: `Got error message: no-speech:` though that may be unrelated.

EDIT: It again stopped TLing after 881 seconds, then opened a new session (I wasn't paying attention so I don't know when that happened relative to when it stopped). However this time it has not started TLing again after opening the session, it's just been sitting there (for at least 4 minutes now as far as I can tell)

**Comment by KentoNishi** [comment]
testing an actual fix rn

**Comment by KentoNishi** [comment]
I figured it out. Basically, the watcher reloads the page every 10 minutes, but the translate api fails to load on reload when not clearing the cache for some reason. Completely removing the refresh interval worked, stream has been running for 16 minutes now.
